export const videoConstants = {
    SEARCH_REQUEST: 'VIDEO_SEARCH_REQUEST',
    SEARCH_SUCCESS: 'VIDEO_SEARCH_SUCCESS',
    SEARCH_FAILURE: 'VIDEO_SEARCH_FAILURE',

    SELECT_REQUEST: 'VIDEO_SELECT_REQUEST',
    SELECT_SUCCESS: 'VIDEO_SELECT_SUCCESS',
    SELECT_FAILURE: 'VIDEO_SELECT_FAILURE',

    PAUSE_REQUEST: 'VIDEO_PAUSE_REQUEST',
    PAUSE_SUCCESS: 'VIDEO_PAUSE_SUCCESS',
    PAUSE_FAILURE: 'VIDEO_PAUSE_FAILURE',

    PLAY_REQUEST: 'VIDEO_PLAY_REQUEST',
    PLAY_SUCCESS: 'VIDEO_PLAY_SUCCESS',
    PLAY_FAILURE: 'VIDEO_PLAY_FAILURE',
};